image: node:16.14

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID

stages:
  - init
  - build
  - test

install:
  variables:
    PROJECT_NAME: admin
    PROJECT_FOLDER: admin
  stage: init
  script: sh init.sh
  artifacts:
    paths:
      - "$PROJECT_FOLDER/node_modules/"

APIRequests:
  variables:
    PROJECT_NAME: APIRequests
    PROJECT_FOLDER: common/utils/APIRequests
  stage: init
  script: sh init.sh
  artifacts:
    paths:
      - "$PROJECT_FOLDER/node_modules/"

build_admin:
  variables:
    PROJECT_NAME: admin
    PROJECT_FOLDER: admin
  stage: build
  script: sh build.sh
  needs:
    - install
    - APIRequests

test_admin:
  variables:
    PROJECT_NAME: admin
    PROJECT_FOLDER: admin
  script: sh tests.sh
