#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "\e[1;93m[pre-commit] Running lint-staged (config is lint-staged.pre-commit.js)\033[0m"
yarn lint-staged -c lint-staged.pre-commit.js
echo "\e[1;93m[pre-commit] Done.\033[0m"
