const loremToFill = `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sagittis nisl rhoncus mattis rhoncus. Est velit egestas dui id ornare. Morbi quis commodo odio aenean sed. Mauris rhoncus aenean vel elit. In ante metus dictum at tempor commodo ullamcorper. Ultrices in iaculis nunc sed augue lacus viverra. Mauris a diam maecenas sed enim ut sem viverra. Nec ultrices dui sapien eget mi proin sed libero. Nunc id cursus metus aliquam eleifend mi in nulla posuere. Sit amet consectetur adipiscing elit ut. Pellentesque sit amet porttitor eget. Elementum pulvinar etiam non quam lacus suspendisse. Mollis aliquam ut porttitor leo. Nec feugiat nisl pretium fusce id velit ut tortor. Egestas maecenas pharetra convallis posuere morbi leo. Vulputate odio ut enim blandit volutpat maecenas volutpat blandit. Dui id ornare arcu odio ut sem.

Mollis nunc sed id semper risus in hendrerit. Bibendum neque egestas congue quisque. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. Quam vulputate dignissim suspendisse in est ante in nibh mauris. Tortor pretium viverra suspendisse potenti nullam ac tortor. Facilisis volutpat est velit egestas dui id. Vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt. Enim praesent elementum facilisis leo vel fringilla est ullamcorper eget. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Erat velit scelerisque in dictum non consectetur. Consequat interdum varius sit amet mattis vulputate. Elementum sagittis vitae et leo duis ut. Blandit massa enim nec dui nunc mattis enim ut. Faucibus a pellentesque sit amet porttitor eget. Congue quisque egestas diam in arcu cursus euismod. Ultrices tincidunt arcu non sodales neque sodales ut. Nisi est sit amet facilisis.

Mattis vulputate enim nulla aliquet porttitor lacus luctus. Dictum at tempor commodo ullamcorper a lacus. Tortor consequat id porta nibh. In pellentesque massa placerat duis ultricies. Malesuada fames ac turpis egestas integer eget aliquet nibh. Consequat mauris nunc congue nisi vitae. Tincidunt praesent semper feugiat nibh sed pulvinar proin. Turpis massa tincidunt dui ut ornare lectus sit. Nunc consequat interdum varius sit amet. Eu lobortis elementum nibh tellus. Elit pellentesque habitant morbi tristique senectus.

Ut porttitor leo a diam sollicitudin tempor id eu. Felis eget velit aliquet sagittis id consectetur. Vitae suscipit tellus mauris a. Pulvinar etiam non quam lacus suspendisse faucibus interdum posuere. Feugiat vivamus at augue eget arcu dictum varius duis. Id volutpat lacus laoreet non curabitur gravida arcu ac tortor. Aliquam nulla facilisi cras fermentum odio. Suspendisse interdum consectetur libero id. Blandit cursus risus at ultrices. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies. Varius sit amet mattis vulputate enim nulla aliquet porttitor lacus. Ipsum nunc aliquet bibendum enim facilisis gravida neque convallis a. Proin sed libero enim sed faucibus turpis in eu mi. Pharetra pharetra massa massa ultricies mi quis. Commodo quis imperdiet massa tincidunt nunc pulvinar. Scelerisque in dictum non consectetur a erat nam at. A pellentesque sit amet porttitor eget.

Nibh ipsum consequat nisl vel pretium lectus quam id. Enim facilisis gravida neque convallis a cras semper auctor. Amet tellus cras adipiscing enim eu turpis. A diam maecenas sed enim ut. Vitae sapien pellentesque habitant morbi tristique. Rutrum quisque non tellus orci. Dictumst quisque sagittis purus sit amet volutpat consequat mauris nunc. Enim blandit volutpat maecenas volutpat blandit aliquam etiam. At volutpat diam ut venenatis tellus in. Lacus sed turpis tincidunt id aliquet. Amet volutpat consequat mauris nunc congue nisi vitae suscipit. Egestas tellus rutrum tellus pellentesque eu tincidunt. Quisque sagittis purus sit amet. Mattis enim ut tellus elementum sagittis vitae et leo duis. Vitae aliquet nec ullamcorper sit amet risus nullam eget. Ac feugiat sed lectus vestibulum mattis. Auctor neque vitae tempus quam pellentesque. Accumsan lacus vel facilisis volutpat est velit egestas dui.

Ultricies lacus sed turpis tincidunt id aliquet risus. Ipsum a arcu cursus vitae congue mauris rhoncus aenean vel. Vitae sapien pellentesque habitant morbi tristique senectus et. Velit sed ullamcorper morbi tincidunt. Sociis natoque penatibus et magnis dis parturient montes. Euismod lacinia at quis risus sed vulputate odio. Consequat semper viverra nam libero. Ac ut consequat semper viverra nam libero justo. Sed felis eget velit aliquet sagittis. Fringilla urna porttitor rhoncus dolor purus non enim praesent. Porta non pulvinar neque laoreet suspendisse interdum consectetur. Feugiat nisl pretium fusce id velit ut tortor pretium. Mattis vulputate enim nulla aliquet porttitor lacus luctus. Et tortor consequat id porta nibh venenatis. Arcu risus quis varius quam quisque id diam vel quam. Leo duis ut diam quam nulla porttitor massa. Ultrices in iaculis nunc sed augue lacus. Eu turpis egestas pretium aenean pharetra magna. Sapien faucibus et molestie ac feugiat sed lectus. Quisque egestas diam in arcu.

Eget mi proin sed libero enim. Scelerisque eleifend donec pretium vulputate sapien nec sagittis aliquam. Id faucibus nisl tincidunt eget nullam non nisi est. Risus ultricies tristique nulla aliquet enim tortor at auctor. Ornare suspendisse sed nisi lacus sed viverra tellus in. Sagittis orci a scelerisque purus semper eget. Amet commodo nulla facilisi nullam vehicula ipsum a. Mauris nunc congue nisi vitae suscipit. Neque viverra justo nec ultrices dui. Elementum nibh tellus molestie nunc non blandit massa enim nec.

Ut lectus arcu bibendum at. Sed risus ultricies tristique nulla. Justo eget magna fermentum iaculis. Massa placerat duis ultricies lacus. Leo urna molestie at elementum eu facilisis. Urna nec tincidunt praesent semper feugiat. Adipiscing tristique risus nec feugiat in fermentum posuere urna. Rhoncus mattis rhoncus urna neque viverra justo. Vitae tortor condimentum lacinia quis vel eros donec ac odio. Vitae nunc sed velit dignissim. Dignissim convallis aenean et tortor. Diam sollicitudin tempor id eu. Platea dictumst vestibulum rhoncus est pellentesque elit. Sed elementum tempus egestas sed. Auctor elit sed vulputate mi. Eu nisl nunc mi ipsum faucibus vitae aliquet nec. Amet consectetur adipiscing elit duis tristique sollicitudin nibh sit amet. Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam.

Sed arcu non odio euismod lacinia at quis risus sed. A arcu cursus vitae congue mauris rhoncus aenean vel elit. Vitae congue eu consequat ac felis donec et. Tempor id eu nisl nunc mi ipsum faucibus vitae aliquet. In vitae turpis massa sed elementum tempus egestas sed sed. Massa tempor nec feugiat nisl pretium fusce id. Scelerisque eu ultrices vitae auctor eu augue ut lectus arcu. Pretium viverra suspendisse potenti nullam ac tortor vitae purus. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Vitae et leo duis ut diam quam. Nunc lobortis mattis aliquam faucibus. Sagittis purus sit amet volutpat. Sed odio morbi quis commodo odio aenean sed adipiscing diam.

Diam maecenas sed enim ut sem viverra aliquet eget sit. Elementum nisi quis eleifend quam adipiscing vitae proin sagittis nisl. Senectus et netus et malesuada fames ac turpis egestas sed. Ac turpis egestas integer eget aliquet nibh praesent tristique magna. Dolor sit amet consectetur adipiscing elit. Luctus accumsan tortor posuere ac. Ac feugiat sed lectus vestibulum mattis ullamcorper. Turpis egestas pretium aenean pharetra magna. Risus at ultrices mi tempus. Enim ut sem viverra aliquet. Eget lorem dolor sed viverra ipsum. Bibendum arcu vitae elementum curabitur vitae. Enim neque volutpat ac tincidunt vitae semper quis lectus nulla. Mi tempus imperdiet nulla malesuada. Vitae elementum curabitur vitae nunc sed. Eu scelerisque felis imperdiet proin.`

function pad(str: string, len: number) {
  const fullStrLen = (str + loremToFill).length
  const repeat = len - fullStrLen > 0 ? Math.ceil((len - fullStrLen) / loremToFill.length) + 1 : 1
  return (str + loremToFill.repeat(repeat)).substring(0, len)
}

export default pad
